apiVersion: v1
kind: ServiceAccount
metadata:
  name: wg-edgerouter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wireguard-peer
rules:
  - apiGroups:
      - wg.mnrz.xyz
    resources:
      - peers
    verbs:
      - get
      - list
      - watch
---
# TODO: make this a RoleBinding instead of ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wg-edgerouter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wireguard-peer
subjects:
  - kind: ServiceAccount
    name: wg-edgerouter
    namespace: wireguard
---
apiVersion: wg.mnrz.xyz/v1alpha1
kind: Network
metadata:
  name: mnrz
spec:
  subnet: 10.30.51.0/24
  allocations:
  # Automatically allocate IP addresses in the given subnet
  - address: 10.30.51.100
    selector:
      names:
      - laptop
  - address: 10.30.51.101
    selector:
      names:
      - james-iphone
  - address: 10.30.51.2
    selector:
      names:
      - edgerouter
---
apiVersion: wg.mnrz.xyz/v1alpha1
kind: Peer
metadata:
  name: laptop
spec:
  endpoint: :12350
  publicKey: GzKzC864lsXsBxk7FcGeXdNh0JdF/0wO54PG8J6VrgM=
---
apiVersion: wg.mnrz.xyz/v1alpha1
kind: Peer
metadata:
  name: james-iphone
spec:
  endpoint: :12350
  publicKey: yG+ThkCbpg1OyXKvkyeiYT92rl3P5gr6F7V5PnQz6GU=
---
apiVersion: wg.mnrz.xyz/v1alpha1
kind: Peer
metadata:
  name: edgerouter
spec:
  endpoint: ddns.home.k8s.co:12345
  publicKey: qMdABrhGqsAX/xejBEz6jAZfN6JROpa5ZfhQ821wukE=
---
apiVersion: wg.mnrz.xyz/v1alpha1
kind: RouteBinding
metadata:
  name: edgerouter
spec:
  routes:
    - 10.30.48.0/24
    - 10.30.49.0/24
    - 10.30.50.0/24
    - 10.30.51.0/24
    - 10.210.38.0/24
  network: mnrz
  selector:
    names:
      - edgerouter
---
apiVersion: wg.mnrz.xyz/v1alpha1
kind: Network
metadata:
  name: marley
spec:
  subnet: 192.168.53.0/24
  allocations:
    # Automatically allocate IP addresses in the given subnet
    - address: 192.168.53.1
      selector:
        names:
          - marley
    - address: 192.168.53.10
      selector:
        names:
          - edgerouter-marley
---
apiVersion: wg.mnrz.xyz/v1alpha1
kind: Peer
metadata:
  name: marley
spec:
  endpoint: 212.69.32.16:12345
  publicKey: 6VHHFqHeIvCsuomnIDHyGeHikquqpALlZKDOI1Tq9FE=
---
apiVersion: wg.mnrz.xyz/v1alpha1
kind: Peer
metadata:
  name: edgerouter-marley
spec:
  endpoint: ddns.home.k8s.co:12346
  publicKey: qMdABrhGqsAX/xejBEz6jAZfN6JROpa5ZfhQ821wukE=
---
apiVersion: wg.mnrz.xyz/v1alpha1
kind: RouteBinding
metadata:
  name: edgerouter-marley
spec:
  routes:
    - 10.210.38.0/24
  network: marley
  selector:
    names:
    - marley
