apiVersion: wg.mnrz.xyz/v1alpha1
kind: Network
metadata:
  name: mnrz
spec:
  subnet: 10.30.51.0/24
---
apiVersion: wg.mnrz.xyz/v1alpha1
kind: Peer
metadata:
  name: laptop
spec:
  endpoint: :12350
  publicKey: GzKzC864lsXsBxk7FcGeXdNh0JdF/0wO54PG8J6VrgM=
status:
  address: 10.30.51.100/24
  network: mnrz
---
apiVersion: wg.mnrz.xyz/v1alpha1
kind: Peer
metadata:
  name: edgerouter
spec:
  endpoint: ddns.home.k8s.co:12345
  publicKey: qMdABrhGqsAX/xejBEz6jAZfN6JROpa5ZfhQ821wukE=
status:
  address: 10.30.51.2/24
  network: mnrz
---
apiVersion: wg.mnrz.xyz/v1alpha1
kind: RouteBinding
metadata:
  name: edgerouter
spec:
  routes:
    - 10.30.48.0/24
    - 10.30.49.0/24
    - 10.30.50.0/24
    - 10.30.51.0/24
    - 10.210.38.0/24
  network: mnrz
  selector:
    names:
      - edgerouter
---
apiVersion: wg.mnrz.xyz/v1alpha1
kind: Network
metadata:
  name: marley
spec:
  subnet: 192.168.53.1/24
---
apiVersion: wg.mnrz.xyz/v1alpha1
kind: Peer
metadata:
  name: marley
spec:
  endpoint: 212.69.32.16:12345
  publicKey: 6VHHFqHeIvCsuomnIDHyGeHikquqpALlZKDOI1Tq9FE=
status:
  address: 192.168.53.1/24
  network: marley
---
apiVersion: wg.mnrz.xyz/v1alpha1
kind: Peer
metadata:
  name: edgerouter-marley
spec:
  endpoint: ddns.home.k8s.co:12346
  publicKey: qMdABrhGqsAX/xejBEz6jAZfN6JROpa5ZfhQ821wukE=
status:
  address: 192.168.53.10/24
  network: marley
---
apiVersion: wg.mnrz.xyz/v1alpha1
kind: RouteBinding
metadata:
  name: edgerouter-marley
spec:
  routes:
    - 10.210.38.0/24
  network: marley
  selector:
    names:
    - marley
