apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: routebindings.wg.mnrz.xyz
spec:
  group: wg.mnrz.xyz
  names:
    kind: RouteBinding
    plural: routebindings
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            routes:
              description: Routes is a list of subnets that should be routed via peers
                matching the given selector. If a peer matches the selector, all routes
                named here will be configured via that peer. If multiple peers match,
                then multiple routes will be created and it is up to the systems routing
                table to decide which route to use.
              items:
                type: string
              type: array
            selector:
              description: Selector selects peers to route traffic to
              properties:
                matchLabels:
                  description: MatchLabels can be used to match Peers. If specified,
                    *all* labels must be present on peers in order for them to match.
                  type: object
                names:
                  description: Names is a list of peer names that match this selector.
                    If multiple names are provided, a Peer 'matches' if its name is
                    contained within this slice.
                  items:
                    type: string
                  type: array
              type: object
          required:
          - selector
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
