apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: networks.wg.mnrz.xyz
spec:
  group: wg.mnrz.xyz
  names:
    kind: Network
    plural: networks
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            allocations:
              description: Rules for allocating IP addresses to peers
              items:
                properties:
                  address:
                    description: Address is a designated static address for this peer.
                    type: string
                  selector:
                    description: Selector matches peers that should be allocated an
                      address using this allocation rule. If not set, this rule will
                      match all peers and act as the default IP allocation mechanism
                      for the Network.
                    properties:
                      matchLabels:
                        description: MatchLabels can be used to match Peers. If specified,
                          *all* labels must be present on peers in order for them
                          to match.
                        type: object
                      names:
                        description: Names is a list of peer names that match this
                          selector. If multiple names are provided, a Peer 'matches'
                          if its name is contained within this slice.
                        items:
                          type: string
                        type: array
                    type: object
                type: object
              type: array
            subnet:
              description: Subnet is the subnet that encompassing this Wireguard network.
                Peer addresses will be automatically assigned out of this subnet.
              type: string
          required:
          - subnet
          type: object
        status:
          properties:
            allocations:
              description: The list of assigned IP addresses for peers
              items:
                properties:
                  address:
                    description: The allocated IP address
                    type: string
                  name:
                    description: The name of the Peer that has been allocated an address
                    type: string
                required:
                - name
                - address
                type: object
              type: array
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
